web_fullstack/firstproject/first_Django/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.contrib.auth import views as auth_views
from first_app import views

urlpatterns = [
    path('', include('first_app.urls')),
    path('admin/', admin.site.urls),
    path('second_app/', include('second_app.urls')),
    path('third_app/', include('third_app.urls')),
    path('form/',include('forms.urls')),
    path('fourth_app/',include('fourth_app.urls')),
    path('', include('user_profile.urls')),

]

web_fullstack/firstproject/first_app/urls.py
from django.urls import path
from first_app import views

app_name = 'first_app'
urlpatterns = [
    path('first_app/', views.index, name='index'),
    path('', views.homepage, name='home'),
]

web_fullstack/firstproject/forms/urls.py
from django.urls import path
from . import views

app_name = 'forms'
urlpatterns = [
    path('', views.form_name_view, name='forms')
]

web_fullstack/firstproject/fourth_app/urls.py
from . import views
from django.urls import path

app_name = 'fourth_app'
urlpatterns = [
    path('', views.fork, name='fork'),
    path('path1/', views.path1, name='path1'),
    path('path2/', views.path2, name='path2'),
]

web_fullstack/firstproject/fourth_app/models.py
from django.db import models

# Create your models here.

web_fullstack/firstproject/fourth_app/views.py
from django.shortcuts import render


# Create your views here.
def fork(request):
    return render(request, 'fourth_app/fork.html')


def path1(request):
    return render(request, 'fourth_app/path1.html')


def path2(request):
    return render(request, 'fourth_app/path2.html')

web_fullstack/firstproject/templates/fourth_app/fork.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block body_block %}
<h1>Which path are you going to take?</h1>
<a href="{% url 'first_app:home' %}">go back to homepage</a>
<ul>
	<li><a href="{% url 'fourth_app:path1' %}">Path 1</a></li>
	<li><a href="{% url 'fourth_app:path2' %}">Path 2</a></li>
</ul>
{% endblock %}}

web_fullstack/firstproject/templates/fourth_app/path1.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block body_block %}
<h1>
	WELCOME TO PATH 1
</h1>
<a href="{% url 'first_app:home' %}">go back to homepage</a>
{% endblock %}

web_fullstack/firstproject/templates/fourth_app/path2.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block body_block %}
<h1>
	WELCOME TO PATH 2
</h1>
<a href="{% url 'first_app:home' %}">go back to homepage</a>
{% endblock %}