web_fullstack/firstproject/first_Django/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.contrib.auth import views as auth_views
from first_app import views

urlpatterns = [
    path('', include('first_app.urls')),
    path('admin/', admin.site.urls),
    path('second_app/', include('second_app.urls')),
    path('third_app/', include('third_app.urls')),
    path('form/',include('forms.urls')),
    path('fourth_app/',include('fourth_app.urls')),
    path('', include('user_profile.urls')),

]

web_fullstack/firstproject/first_app/urls.py
from django.urls import path
from first_app import views

app_name = 'first_app'
urlpatterns = [
    path('first_app/', views.index, name='index'),
    path('', views.homepage, name='home'),
]

web_fullstack/firstproject/forms/urls.py
from django.urls import path
from . import views

app_name = 'forms'
urlpatterns = [
    path('', views.form_name_view, name='forms')
]

web_fullstack/firstproject/fourth_app/urls.py
from . import views
from django.urls import path

app_name = 'fourth_app'
urlpatterns = [
    path('', views.fork, name='fork'),
    path('path1/', views.path1, name='path1'),
    path('path2/', views.path2, name='path2'),
]

web_fullstack/firstproject/second_app/urls.py
from django.conf.urls import url
from second_app import views

app_name = 'second_app'
urlpatterns = [
    url(r'^$', views.help, name='help')
]

web_fullstack/firstproject/third_app/urls.py
from django.urls import path
from third_app import views

app_name = 'third_app'
urlpatterns = [
    path('', views.users, name='users')
]

web_fullstack/firstproject/user_profile/urls.py
from django.urls import path
from . import views

app_name = 'user_profile'
urlpatterns = [
    path('register/', views.register, name='register'),
    path('logout/', views.user_logout, name='logout'),
    path('login/', views.user_login, name='login'),
]

web_fullstack/firstproject/first_app/models.py
from django.db import models


# Create your models here.
class Topic(models.Model):
    top_name = models.CharField(max_length=264, unique=True)

    def __str__(self):
        return self.top_name


class Webpage(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    name = models.CharField(max_length=264, unique=True)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.name


class Accessrecord(models.Model):
    name = models.ForeignKey(Webpage, on_delete=models.CASCADE)
    date = models.DateField()

    def __str__(self):
        return str(self.date)

web_fullstack/firstproject/forms/models.py
from django.db import models

# Create your models here.

web_fullstack/firstproject/fourth_app/models.py
from django.db import models

# Create your models here.

web_fullstack/firstproject/second_app/models.py
from django.db import models

# Create your models here.

web_fullstack/firstproject/third_app/models.py
from django.db import models


# Create your models here.

class Users(models.Model):
    first_name = models.CharField(max_length=105)
    last_name = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)

    def __str__(self):
        return self.first_name

web_fullstack/firstproject/forms/admin.py
from django.contrib import admin

# Register your models here.

web_fullstack/firstproject/forms/apps.py
from django.apps import AppConfig


class FormsConfig(AppConfig):
    name = 'forms'

web_fullstack/firstproject/forms/forms.py
from django import forms
from django.core import validators

def custom_validator(value):
    if value[0].lower != 'z':
        raise forms.ValidationError('NAME MUST START WITH Z')


class FormName(forms.Form):
    name = forms.CharField(max_length=100)
    email = forms.EmailField(max_length=100)
    verify_email = forms.EmailField(max_length=100,label='Enter your email again',required=True)
    text = forms.CharField(widget=forms.Textarea)
    botcatcher = forms.CharField(
        widget=forms.HiddenInput,
        required=False,
        validators=[validators.MaxLengthValidator(0)])

    def clean(self):
        all_clean_data = super().clean()
        email = all_clean_data['email']
        vmail = all_clean_data['verify_email']
        if email!= vmail:
            raise forms.ValidationError('MAKE SURE EMAIL MATCH')

    # def clean_botcatcher(self):
    #     botcatcher = self.cleaned_data['botcatacher']
    #     if len(botcatcher)>0:
    #         raise forms.ValidationError("GOTCHA BOT!")

web_fullstack/firstproject/forms/tests.py
from django.test import TestCase

# Create your tests here.

web_fullstack/firstproject/forms/views.py
from django.shortcuts import render
from . import forms


# Create your views here.

def form_name_view(request):
    form = forms.FormName()

    if request.method == 'POST':
        form = forms.FormName(request.POST)
        if form.is_valid():
            print('VALIDATION SUCCESS')
            print('NAME '+ form.cleaned_data['name'])
            print('EMAIL ' + form.cleaned_data['email'])
            print('TEXT ' + form.cleaned_data['text'])

    return render(request, 'forms/forms.html', {'form': form})

web_fullstack/firstproject/third_app/forms.py
from django import forms
from .models import Users


class UserForm(forms.ModelForm):
    class Meta:
        model = Users
        fields = '__all__'

web_fullstack/firstproject/first_app/views.py
from django.shortcuts import render
from django.http import HttpResponse
from first_app.models import Topic, Webpage, Accessrecord


# Create your views here.
def index(request):
    my_dict = {
        'insert_me': 'Hello I am from views.py'
    }

    webpages_list = Accessrecord.objects.order_by('date')

    date_dict = {
        'access_dates': webpages_list
    }
    return render(request, 'first_app/index.html', context=date_dict)

def homepage(request):
    return render(request, 'first_app/homepage.html')

web_fullstack/firstproject/fourth_app/views.py
from django.shortcuts import render


# Create your views here.
def fork(request):
    return render(request, 'fourth_app/fork.html')


def path1(request):
    return render(request, 'fourth_app/path1.html')


def path2(request):
    return render(request, 'fourth_app/path2.html')

web_fullstack/firstproject/second_app/views.py
from django.shortcuts import render


def help(request):
    my_dict = {
        'help_needed': 10
    }
    return render(request, 'second_app/help.html', context=my_dict)

web_fullstack/firstproject/third_app/views.py
from django.shortcuts import render
from third_app.models import Users
from . import forms
from first_app import views


# Create your views here.

def users(request):
    obj = Users.objects.all()
    form = forms.UserForm()

    dict = {
        'users': obj,
        'form': form
    }

    if request.method == 'POST':
        form = forms.UserForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            # return views.homepage(request)
            # fn = form.cleaned_data['first_name']
            # ln = form.cleaned_data['last_name']
            # em = form.cleaned_data['email']
            # t = Users.objects.get_or_create(first_name=fn, last_name=ln, email=em)[0]
            # t.save()

    return render(request, 'third_app/users.html', context=dict)

web_fullstack/firstproject/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title></title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
	      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	<a class="navbar-brand" href="#"><img src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg"
	                                      width="30" height="30"
	                                      class="d-inline-block align-top" alt="">
		Bootstrap</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
	        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span>
	</button>

	<div class="collapse navbar-collapse" id="navbarSupportedContent">
		<ul class="navbar-nav mr-auto">
			<li class="nav-item active">
				<a class="nav-link" href="{% url 'first_app:home' %}">Home <span class="sr-only">(current)</span></a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'first_app:index' %}">First</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'second_app:help' %}">Second</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'third_app:users' %}">Third</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'fourth_app:fork' %}">Fourth</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'forms:forms' %}">Form</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{% url 'user_profile:register' %}">Register</a>
			</li>

			{% if user.is_authenticated %}
			<li class="nav-item">
				<a class="nav-link" href="{% url 'user_profile:logout' %}">Logout</a>
			</li>
			{% else %}
			<li class="nav-item">
				<a class="nav-link" href="{% url 'user_profile:login' %}">Login</a>
			</li>
			{% endif %}

		</ul>
	</div>
</nav>

<div class="container">
	{% block body_block %}

	{% endblock%}
</div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>
</html>